Moved warn messages from bashrc to configuring scripts.

diff --git a/app-shells/bash/files/dot-bashrc b/app-shells/bash/files/dot-bashrc
--- a/app-shells/bash/files/dot-bashrc
+++ b/app-shells/bash/files/dot-bashrc
@@ -14,10 +14,6 @@ if [[ $- =~ "i" && $USER == "smilart" ]]; then
         network-config;
         if [[ $? == 0 ]];then
             touch $PATH_CONFIGURE_DIR/network_installed;
-        else
-            echo;
-            echo -e "\E[33mWARN: Network is not configured.";tput sgr0;
-            sleep 1;
         fi;
     fi;
 
@@ -26,10 +22,6 @@ if [[ $- =~ "i" && $USER == "smilart" ]]; then
         datetime-config;
         if [[ $? == 0 ]];then
             touch $PATH_CONFIGURE_DIR/datetime_installed;
-        else
-            echo;
-            echo -e "\E[33mWARN: Time is not configured.";tput sgr0;
-            sleep 1;
         fi;
     fi;
 
@@ -38,10 +30,6 @@ if [[ $- =~ "i" && $USER == "smilart" ]]; then
         cluster-config;
         if [[ $? == 0 ]];then
             touch $PATH_CONFIGURE_DIR/cluster_installed;
-        else
-            echo;
-            echo -e "\E[33mWARN: Cluster is not configured.";tput sgr0;
-            sleep 1;
         fi;
     fi;
 
@@ -60,9 +48,9 @@ if [[ $- =~ "i" && $USER == "smilart" ]]; then
         touch $PATH_CONFIGURE_DIR/product_installed;
         sudo /opt/bin/installproduct;
         if [ $? -ne 0 ];then
-            echo -e "\E[31mERROR: Product is not installed correctly." >&2;tput sgr0;
+            echo -e "\E[31mERROR: Product is not installed correctly.\n" >&2;tput sgr0;
         else
-            echo -e "\E[32mInstallation is completed.";tput sgr0;
+            echo -e "\E[32mInstallation is completed.\n";tput sgr0;
         fi;
 
         # Rebooting system
